### ISSUE TITLE
Requests are not logged

### ISSUE THREAD

**Issue by benlangfeld** [polysics/virginia#20]
Rack should log all requests (timestamp, HTTP verb, path, and response code) regardless of the application's specific logging, but an Adhearsion app using Virginia appears not to log anything on requests.

See http://www.rubydoc.info/github/rack/rack/master/Rack/CommonLogger

It seems that `Adhearsion.logger << "foo"` never prints anything to the log.

**Comment by bklang** [comment]
With #21 merged, can this be closed?
